# Generated by Django 5.2.7 on 2025-10-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='お名前')),
                ('message', models.CharField(max_length=120, verbose_name='メッセージ')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
            ],
            options={
                'db_table': 'comment',
                'ordering': ('-date',),
            },
        ),
    ]
